export const ROLES = {
  JEFATURA: 'JEFATURA',
  DIRECTOR: 'DIRECTOR',
  AYUDANTE: 'AYUDANTE',
};

export const ESTADOS_BITACORA = {
  BORRADOR: 'BORRADOR',
  ENVIADA: 'ENVIADA',
  APROBADA: 'APROBADA',
  RECHAZADA: 'RECHAZADA',
};

export const ESTADOS_CONTRATO = {
  ACTIVO: 'ACTIVO',
  INACTIVO: 'INACTIVO',
};

export const MOTIVOS_FINALIZACION = {
  RENUNCIA: 'RENUNCIA',
  FIN_CONTRATO: 'FIN_CONTRATO',
  DESPIDO: 'DESPIDO',
};

export const TIPOS_PROYECTO = {
  INVESTIGACION: 'INVESTIGACION',
  VINCULACION: 'VINCULACION',
  TRANSFERENCIA_TECNOLOGICA: 'TRANSFERENCIA_TECNOLOGICA',
};

export const SUBTIPOS_PROYECTO = {
  INTERNO: 'INTERNO',
  SEMILLA: 'SEMILLA',
  GRUPAL: 'GRUPAL',
  MULTIDISCIPLINARIO: 'MULTIDISCIPLINARIO',
};

export const TIPOS_AYUDANTE = {
  ASISTENTE_INVESTIGACION: 'ASISTENTE_INVESTIGACION',
  AYUDANTE_INVESTIGACION: 'AYUDANTE_INVESTIGACION',
  TECNICO_INVESTIGACION: 'TECNICO_INVESTIGACION',
};

export const COLORES_SEMAFORO = {
  VERDE: { bg: 'bg-green-100', text: 'text-green-800', border: 'border-green-300' },
  AMARILLO: { bg: 'bg-yellow-100', text: 'text-yellow-800', border: 'border-yellow-300' },
  ROJO: { bg: 'bg-red-100', text: 'text-red-800', border: 'border-red-300' },
};