server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: sistema-dicc-backend

  datasource:
    url: jdbc:sqlite:./data/sistema_dicc.db
    driver-class-name: org.sqlite.JDBC

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/seed.sql

management:
  endpoints:
    web:
      exposure:
        include: health,info
